export const profile = {
  name: "Lumu Francis Xavier",
  location: "Kampala, Uganda",
  university: "International University of East Africa",
  degree: "B.Sc. Software Engineering",
  github: "https://github.com/lumuxav",
  whatsapp: "https://wa.me/256757742177",
  whatsappDisplay: "0757 742 177",
  instagram: "https://www.instagram.com/_l.u.m.u_/",
  portrait: "/lumu-portrait.webp",
};

export const projects = [
  {
    id: "rentalhub",
    number: "01",
    title: "RentalHub",
    category: "Full-stack product",
    status: "Deployed project",
    summary: "A rental marketplace built around the way people actually search, list and discover places to live.",
    detail: "A dual-role marketplace with dedicated host and guest journeys, responsive product flows and a modern front-end architecture designed to make the rental experience feel simple on any screen.",
    role: "Application development & interface design",
    stack: ["React", "Vite", "Vercel", "Responsive UI"],
    highlights: [
      "Separate host and guest experiences",
      "Responsive layouts for mobile and desktop",
      "Deployment and production workflow on Vercel",
    ],
  },
  {
    id: "aquasentinel",
    number: "02",
    title: "AquaSentinel-ML",
    category: "AI & computer vision",
    status: "Team project · IUEA-Labs",
    summary: "Computer vision that turns aquaculture video into trackable, per-fish health intelligence.",
    detail: "An applied ML system built with the IUEA-Labs AI Team. YOLO detects fish, ByteTrack maintains identities and a BiLSTM with attention classifies temporal behaviour so the dashboard can move from raw footage toward useful health insight.",
    role: "Junior AI team member · applied ML development",
    stack: ["Python", "YOLO", "ByteTrack", "BiLSTM", "Streamlit"],
    highlights: [
      "Webcam, IP camera and uploaded-video inputs",
      "Live tracking and per-fish disease indicators",
      "Investigated tracking stability and synthetic-data behaviour",
    ],
  },
  {
    id: "maya-steel",
    number: "03",
    title: "Maya Steel Works",
    category: "Business system",
    status: "Active build",
    summary: "An operations system shaped around real sales, fabrication services and branch-specific workflows.",
    detail: "A practical management system for recording sales, tracking worked customer materials, payments and operational records without forcing the business into generic workflows that do not match how the branch actually works.",
    role: "System design, workflow modelling & implementation",
    stack: ["Business logic", "Database", "Dashboard", "Workflow UX"],
    highlights: [
      "Sales and service recording for different material scenarios",
      "Payment and plate-work tracking",
      "Single-branch logic to reduce operational confusion",
    ],
  },
  {
    id: "sm-engineering",
    number: "04",
    title: "SM Engineering Works",
    category: "Client platform",
    status: "Real client work",
    summary: "A clearer digital front door for an engineering business with very hands-on services.",
    detail: "A client website covering industrial motor repair, metal fabrication and electronics repair, refined around the company’s actual service categories, contact needs and WhatsApp lead flow.",
    role: "Website development & client iteration",
    stack: ["HTML", "CSS", "JavaScript", "WhatsApp"],
    highlights: [
      "Service-led information architecture",
      "Responsive design and animated interactions",
      "Direct WhatsApp enquiry flow",
    ],
  },
  {
    id: "elevation-academy",
    number: "05",
    title: "Elevation Academy",
    category: "Web application",
    status: "Client project",
    summary: "A polished multi-page coaching and mentorship platform designed to grow into payments and member journeys.",
    detail: "A seven-page responsive React experience for a mentorship brand, structured for clear programmes, conversion-focused content and future payment integration using Uganda-friendly mobile money options.",
    role: "Front-end development & product structure",
    stack: ["React", "Vite", "Netlify", "Payments-ready"],
    highlights: [
      "Responsive component system",
      "Multi-page information architecture",
      "Deployment and payment-integration planning",
    ],
  },
  {
    id: "dj-rossi-wine",
    number: "06",
    title: "DJ Rossi Wine",
    category: "Creator platform",
    status: "Deployed build",
    summary: "A media-led DJ website that combines brand presentation, video, services and an administration workflow.",
    detail: "A performance-focused personal brand site developed with media-heavy sections, service presentation and dashboard-backed content needs, then adapted for reliable static hosting and deployment on Netlify.",
    role: "Full website build, deployment & debugging",
    stack: ["HTML", "CSS", "JavaScript", "Netlify"],
    highlights: [
      "Media-first hero and services experience",
      "Hosting and asset-path troubleshooting",
      "Backend-to-static deployment adaptation",
    ],
  },
  {
    id: "network-labs",
    number: "07",
    title: "Network Labs",
    category: "Networking & automation",
    status: "Hands-on labs",
    summary: "Routing, naming, segmentation and automation beneath the applications people see.",
    detail: "Linux network environments in GNS3 with Bash automation for DHCP and DNS using dnsmasq, alongside Cisco work covering multi-switch VLAN/VTP design and inter-VLAN routing.",
    role: "Network configuration & Linux automation",
    stack: ["GNS3", "Cisco IOS", "Linux", "Bash", "dnsmasq"],
    highlights: [
      "DHCP and DNS provisioning with Bash",
      "VLAN segmentation and inter-VLAN routing",
      "Ubuntu Server and Alpine Linux administration",
    ],
  },
];

export const experiments = [
  {
    title: "WhatsApp AI assistant",
    description: "A conversational class project connecting WhatsApp messages to Gemini through a Node.js and Express backend.",
    stack: "Node.js / Express / Meta API / Gemini",
  },
  {
    title: "Browser battle royale",
    description: "Canvas-based gameplay experiments covering zone timing, damage registration, movement and spawn logic.",
    stack: "JavaScript / HTML5 Canvas",
  },
  {
    title: "Local AI workspace",
    description: "An offline coding workflow on Fedora that connects a local Ollama model to VS Code through Continue.",
    stack: "Ollama / Linux / VS Code",
  },
  {
    title: "School technology concept",
    description: "Exploring a connected admissions and school-fees system that can reconcile student balances with payment events.",
    stack: "Systems thinking / Database / Payments",
  },
];
